# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

AnoLectivo.create(ano_lectivo: "2012/2013") 

User.create(username: 'ftpaul', password: 'senha')

Curso.create(id: 19, designacao: "ERASMUS")
Curso.create(id: 21, designacao: "LEI")
Curso.create(id: 22, designacao: "FC")
Curso.create(id: 23, designacao: "PSI")
Curso.create(id: 24, designacao: "SOC")
Curso.create(id: 25, designacao: "IGE")
Curso.create(id: 26, designacao: "ETI")
Curso.create(id: 27, designacao: "ECO")
Curso.create(id: 28, designacao: "MKT")
Curso.create(id: 29, designacao: "GES")
Curso.create(id: 30, designacao: "ANT")
Curso.create(id: 31, designacao: "Serviço Social")
Curso.create(id: 32, designacao: "PL")
Curso.create(id: 33, designacao: " ")
Curso.create(id: 34, designacao: "ARQ")
Curso.create(id: 35, designacao: "Ciência Politica")
Curso.create(id: 36, designacao: "MDDLPM")
Curso.create(id: 37, designacao: "Mestrado DDLMP")
Curso.create(id: 38, designacao: "uiu")
Curso.create(id: 39, designacao: "M.CPO")
Curso.create(id: 40, designacao: "GEI")
Curso.create(id: 41, designacao: "HMC")
Curso.create(id: 42, designacao: "M.CONT.")
Curso.create(id: 43, designacao: "M.PSI.S.O.")
Curso.create(id: 44, designacao: "M.Finanças")
Curso.create(id: 45, designacao: "M.D.E.")
Curso.create(id: 46, designacao: "GRH")
Curso.create(id: 47, designacao: "M.E.I.")
Curso.create(id: 48, designacao: "M. Cont.")
Curso.create(id: 49, designacao: "M. ESS")
Curso.create(id: 50, designacao: "M.GRH")
Curso.create(id: 51, designacao: "M.HMC")
Curso.create(id: 52, designacao: "Eng.Inf.")
Curso.create(id: 53, designacao: "PG. IAO")
Curso.create(id: 54, designacao: "M.ETI")
Curso.create(id: 55, designacao: "MIA")
Curso.create(id: 56, designacao: "MPSO")
Curso.create(id: 57, designacao: "M.S.S.")
Curso.create(id: 58, designacao: "M.I.G.")
Curso.create(id: 59, designacao: "Edu.Sociedade")
Curso.create(id: 60, designacao: "M.Gestão")
Curso.create(id: 61, designacao: "M.GEC")
Curso.create(id: 62, designacao: "M.E.P.P.")
Curso.create(id: 63, designacao: "Finanças")
Curso.create(id: 64, designacao: "M.GST")
Curso.create(id: 65, designacao: "M.Antr.")
Curso.create(id: 66, designacao: "M.C.C.")
Curso.create(id: 67, designacao: "M.EMF")
Curso.create(id: 68, designacao: "M.MKT")
Curso.create(id: 69, designacao: "M.GSI")
